name: "Spritter"
version: "1.0.14"
slug: "spritter"
description: Fuel price getter with MQTT support
url: https://github.com/spritter-org/spritter-ha
startup: application
boot: auto
init: false
ingress: false
services:
  - "mqtt:need"
arch:
  - aarch64
  - amd64
options:
  refresh_interval_minutes: 5
  stations: []
schema:
  refresh_interval_minutes: int(1,10080)
  stations:
    - name: str
      provider: str
      station_id: str
      keys:
        - str?